### ISSUE TITLE
ARM64 Terraform cannot be downloaded if OS reports its arch as Aarch64

### ISSUE THREAD

**Issue by fishfacemcgee** [AzBuilder/terraform-spring-boot#52]
I'm attempting to run Terrakube on EKS using ARM-based nodes, and the Executor is unable to download Terraform. Pulling the container logs and I get the following:

```
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl - Terraform Working Directory: /root/.terraform-spring-boot/executor/a682c11d-7fa1-4a20-b73f-4ab488d9cb24/a42c0089-2d52-4f8e-9f27-145b16cbae5b
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.plugin.tfstate.aws.AwsTerraformStateImpl - Generating backend override file for terraform 1.9.8
[threadPoolTaskExecutor-1] WARN org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl - Not using any SSH key to download modules
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformClient - Creating terraform downloader using terraform release URL: https://releases.hashicorp.com/terraform/index.json and tofu release URL: http://terrakube-api-service:8080/tofu/index.json
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Initialize TerraformDownloader using custom URL
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - User Home Directory: /root
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Validate/Create download temp directory: /root/.terraform-spring-boot/download/
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Validate/Create terraform directory: /root/.terraform-spring-boot/terraform/
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - User Home Directory for tofu download: /root
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Validate/Create tofu download temp directory: /root/.terraform-spring-boot/download/tofu/
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Validate/Create tofu directory: /root/.terraform-spring-boot/tofu/
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Downloading terraform releases list
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Deleting Temp /root/.terraform-spring-boot/terraform-10306814652704127386-release
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Found 346 terraform releases
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Downloading tofu releases list
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Deleting Temp /root/.terraform-spring-boot/tofu-18428381804482887821-release
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Found 30 tofu releases
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Downloading terraform version 1.9.8 architecture aarch64 Type Linux
[threadPoolTaskExecutor-1] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(org.terrakube.executor.service.mode.TerraformJob)
java.lang.IllegalArgumentException: Invalid Terraform Version
	at org.terrakube.terraform.TerraformDownloader.downloadTerraformVersion(TerraformDownloader.java:243)
	at org.terrakube.terraform.TerraformClient.getTerraformLauncher(TerraformClient.java:283)
	at org.terrakube.terraform.TerraformClient.run(TerraformClient.java:208)
	at org.terrakube.terraform.TerraformClient.init(TerraformClient.java:104)
	at org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl.executeTerraformInit(TerraformExecutorServiceImpl.java:404)
	at org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl.plan(TerraformExecutorServiceImpl.java:107)
	at org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(ExecutorJobImpl.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

According to [this line](https://github.com/AzBuilder/terraform-spring-boot/blob/afa3236fc58da96f40c2a29d575f163df19fdebd/terraform-client/src/main/java/org/terrakube/terraform/TerraformDownloader.java#L217), the architecture check is a completely strict check, but Terraform lilsts its ARM versions as `arm` and `arm64`, so `aarch64` will never match. Either how the client checks the OS version needs to change to match `dpkg --print-architecture` (see below), or a condition similar to the OS ones needs to be performed.

```
root@terrakube-executor-5654669d77-ksdkm:/workspace# dpkg --print-architecture
arm64
root@terrakube-executor-5654669d77-ksdkm:/workspace# uname -m
aarch64
```

**Comment by alfespa17** [comment]
Hello @fishfacemcgee 

I think the library will have to add some condition in the logic to fix that.

Would you like to help with the fix?

**Comment by fishfacemcgee** [comment]
@alfespa17 I can write what I think a fix would look ilke (assuming we mean this library and not system utils or something), but I don't have any viable means to test the changes myself.

**Comment by alfespa17** [comment]
> @alfespa17 I can write what I think a fix would look ilke (assuming we mean this library and not system utils or something), but I don't have any viable means to test the changes myself.

Ok, let me see if I can create a VM that is using aarch64 and test it there because I have some small example to test the library.

**Comment by alfespa17** [comment]
Hello @fishfacemcgee I created a new release with your fix, it takes some time to be available in maven central, I will update the library in our Terrakube repo in a couple of hours so I can  create maybe a hotfix 2.23.3
